version: '3'

services:
  traefik:
    # The latest official supported Traefik docker image
    image: traefik:v2.3
    # Enables the Traefik Dashboard and tells Traefik to listen to docker
    # enable --log.level=INFO so we can see what Traefik is doing in the log files
    ports:
      # Exposes port 80 for incomming web requests
      - "80:80"
      - "443:443"
      # The Web UI port http://0.0.0.0:8080 (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
    environment:
      - DO_AUTH_TOKEN=

# Add the catapp service
  catapp:
     # A Random Cat GIF generator application
    image: mikesir87/cats:1.0
     # We set a label to tell Traefik to assign a hostname to the new service
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cats.rule=Host(`subdomain.domain.com`)"
      - "traefik.http.routers.cats.entrypoints=websecure"
      - "traefik.http.routers.cats.service=cats"
      - "traefik.http.services.cats.loadbalancer.server.port=5000"
      - "traefik.http.routers.cats.tls.certresolver=catResolver"